### PR TITLE
Debug static indices computing in TrailingAverageCoupler

### PR DESCRIPTION
**Pull request by ivanauyeung**
When the "+1" is there, assume the time step is 48H and 96H, b = 0 and interval = 48H, the coupled index will be 96H and 144H  which is not correct as my understanding. So when deleting "+1", the coupled index will be 48H and 96H as normal.

### CODE REVIEW

**Review by nathanielcresswellclay — CHANGES_REQUESTED** [review]
To create coupled inputs for initializing the ocean at t_0 we want to average the atmospheric timesteps slice(t_0,t_0+48) and slice(t_0+48,t_0-96). We need the increment +1 here to achieve this.

**Comment by ivanauyeung** [comment]
But the input_times for ocean model is ["48H", "96H"], interval is "48H". So if "+1" is kept, 
self._coupled_offsets[0,0,0] = (0+1)*"48H" + "48H" = "96H"
self._coupled_offsets[0,0,1] = (0+1)*"48H" + "96H" = "144H"
In forcasting, the code is averaging the atmospheric timesteps slice(t_0,t_0+48) and slice(t_0+48,t_0+96).
But in training, it use the following values:
coupling_temp = ds_index_range.isel(time=self._coupled_offsets[b,i,:]) 
But from the _coupled_offsets above, it is "96H" and "144H" value so if "+1" is kept, input_times should be "0H" and "48H"? for example,
self._coupled_offsets[0,0,0] = (0+1)*"48H" + "0H" = "48H"
self._coupled_offsets[0,0,1] = (0+1)*"48H" + "48H" = "96H"

**Comment by nathanielcresswellclay** [comment]
Aha! I understand the confusion. 

In this context the offsets are being computed with respect to the **beginning of the batch** (not initialization time). 

Suppose the batch starts it index 0: The first SST input into the model will be indices [0,16] which correspond to times [t_0-48,t_0]. The coupled indices **with respect to the beginning of the batch** are [32,48] which correspond to times [t_0+48,t_0+96]. 

To fully appreciate what these indices mean you can checkout `construct_integrated_couplings` method of the coupler (line 339 of https://github.com/nathanielcresswellclay/zephyr/blob/dlesm/training/dlwp/data/couplers.py) and the iterator method of the dataloader (line 623 of https://github.com/nathanielcresswellclay/zephyr/blob/dlesm/training/dlwp/data/data_loading.py) 

Let me know if there's any more confusion!

**Comment by ivanauyeung** [comment]
Thanks a lot. Now I am clear about the indexing. I will close this PR.

**Pull request closed without merging**
